### ISSUE TITLE
Crear Persistencia con Esclavos Caídos

### ISSUE THREAD

**Issue by WilbertAlfonso** [WilbertAlfonso/Final_Redes#1]
Debes hacer que el Servidor Maestro Mande mensajes constantemente a los Esclavos para ver si están vivos (Usa threads) Si un esclavo se detecta como caído cambiar su atributo activo en la tabla de esclavos.
Supongo que solo modificaras los archivos master.h , nodo.h, Esclavo_info.h y tal vez base.h

**Comment by SebastianWilde** [comment]
Completado, para compilarlo agregar -pthread al final, para teste está imprimiendo los nodos que estan conectados y los que no. Esto se puede comentar para que no este molestando.
Revisa @WilbertAlfonso
